contacts/urls.py
from django.urls import path
from .views import (
    ContactListView,
    ContactView,
    ContactCreateView,
    ContactUpdateView,
    ContactPhoneView,
    ContactPhoneListView,
    ContactPhoneCreateView,
    ContactPhoneUpdateView,
    ContactEmailView,
    ContactEmailListView,
    ContactEmailCreateView,
    ContactEmailUpdateView,
)

app_name = 'contacts'
urlpatterns = [
    path('', ContactListView.as_view(), name='contact-list'),
    path('<pk>', ContactView.as_view(), name='contact-detail'),
    path('new/', ContactCreateView.as_view(), name='contact-create'),
    path('edit/<pk>', ContactUpdateView.as_view(), name='contact-update'),
    path('<contact_pk>/phone/', ContactPhoneListView.as_view(), name='phone'),
    path('<contact_pk>/phone/new/', ContactPhoneCreateView.as_view(), name='phone-create'),
    path('<contact_pk>/phone/<pk>', ContactPhoneView.as_view(), name='phone-detail'),
    path('<contact_pk>/phone/edit/<pk>', ContactPhoneUpdateView.as_view(), name='phone-update'),
    path('<contact_pk>/mail/', ContactEmailListView.as_view(), name='email'),
    path('<contact_pk>/mail/<pk>', ContactEmailView.as_view(), name='email-detail'),
    path('<contact_pk>/mail/new/', ContactEmailCreateView.as_view(), name='email-create'),
    path('<contact_pk>/mail/edit/<pk>', ContactEmailUpdateView.as_view(), name='email-update'),
]

contacts_project/urls.py
from django.contrib import admin
from django.urls import include, path,reverse_lazy

from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, request):
        return reverse_lazy('contacts:contact-list')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls', namespace='contacts')),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
]

contacts/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse

__all__ = (
    'Contact',
    'ContactPhone',
    'ContactEmail',
)


class Contact(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=128)

    def get_absolute_url(self):
        return reverse('contacts:contact-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class ContactPhone(models.Model):
    contact = models.ForeignKey('Contact', on_delete=models.CASCADE)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list

    def get_absolute_url(self):
        return reverse('contacts:phone-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.phone_number


class ContactEmail(models.Model):
    contact = models.ForeignKey('Contact', on_delete=models.CASCADE)
    email = models.EmailField()

    def get_absolute_url(self):
        return reverse('contacts:email-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.email

contacts/views/contact.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    detail,
    edit,
    list as _list,
)
from django.urls import reverse_lazy
from ..models import Contact

__all__ = (
    'ContactListView',
    'ContactView',
    'ContactCreateView',
    'ContactUpdateView',
)


class OwnContactsMixin:
    def get_queryset(self):
        own_contacts = (
            self.model.objects
            .filter(
                user=self.request.user
            )
        )
        return own_contacts


class ContactListView(LoginRequiredMixin, OwnContactsMixin, _list.ListView):
    model = Contact
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'


class ContactView(LoginRequiredMixin, OwnContactsMixin, detail.DetailView):
    model = Contact
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'


class ContactCreateView(LoginRequiredMixin, edit.CreateView):
    model = Contact
    fields = ['name']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

    def form_valid(self, form):
        current_user = self.request.user
        form.instance.user = current_user
        return super().form_valid(form)


class ContactUpdateView(LoginRequiredMixin, edit.UpdateView):
    model = Contact
    fields = ['name']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

contacts/views/email_contact.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    detail,
    edit,
    list as _list,
)
from django.urls import reverse_lazy
from ..models import (
    Contact,
    ContactEmail
)

__all__ = (
    'ContactEmailView',
    'ContactEmailListView',
    'ContactEmailCreateView',
    'ContactEmailUpdateView',
)

class OwnMailsMixin:
    def get_queryset(self):
        contact_emails_accounts = (
            self.model.objects
            .filter(
                contact_id=self.kwargs.get('contact_pk')
            )
        )
        return contact_emails_accounts


class ContactEmailListView(LoginRequiredMixin, OwnMailsMixin, _list.ListView):
    model = ContactEmail
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        contact_id = self.kwargs.get('contact_pk')
        contact = Contact.objects.get(id=contact_id)
        context.update(contact=contact)
        return context


class ContactEmailView(LoginRequiredMixin, OwnMailsMixin, detail.DetailView):
    model = ContactEmail
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'


class ContactEmailCreateView(LoginRequiredMixin, edit.CreateView):
    model = ContactEmail
    fields = ['email']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

    def form_valid(self, form):
        contact_pk = self.kwargs.get('contact_pk')
        current_contact = Contact.objects.get(pk=contact_pk)
        form.instance.contact = current_contact
        return super().form_valid(form)


class ContactEmailUpdateView(LoginRequiredMixin, edit.UpdateView):
    model = ContactEmail
    fields = ['email']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

contacts/views/phone_contact.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    detail,
    edit,
    list as _list,
)
from django.urls import reverse_lazy
from ..models import (
    Contact,
    ContactPhone
)

__all__ = (
    'ContactPhoneListView',
    'ContactPhoneView',
    'ContactPhoneCreateView',
    'ContactPhoneUpdateView',
)


class OwnPhonesMixin:
    def get_queryset(self):
        contact_phones = (
            self.model.objects
            .filter(
                contact_id=self.kwargs.get('contact_pk')
            )
        )
        return contact_phones


class ContactPhoneListView(LoginRequiredMixin, OwnPhonesMixin, _list.ListView):
    model = ContactPhone
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        contact_id = self.kwargs.get('contact_pk')
        contact = Contact.objects.get(id=contact_id)
        context.update(contact=contact)
        return context


class ContactPhoneView(LoginRequiredMixin, OwnPhonesMixin, detail.DetailView):
    model = ContactPhone
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'


class ContactPhoneCreateView(LoginRequiredMixin, edit.CreateView):
    model = ContactPhone
    fields = ['phone_number']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

    def form_valid(self, form):
        contact_pk = self.kwargs.get('contact_pk')
        current_contact = Contact.objects.get(pk=contact_pk)
        form.instance.contact = current_contact
        return super().form_valid(form)


class ContactPhoneUpdateView(LoginRequiredMixin, edit.UpdateView):
    model = ContactPhone
    fields = ['phone_number']
    success_url = reverse_lazy('contacts:contact-list')
    login_url = reverse_lazy('auth_login')
    redirect_field_name = 'redirect_to'

contacts/templates/contacts/base.html
{% extends "base.html" %}
{% block content %}
<div>
	bienvenido {{ request.user }}, <a href="{% url 'auth_logout' %}?next={% url 'auth_login' %}">logout</a>
</div>
{% block subcontent %}
{% endblock subcontent %}
{% endblock content %}

contacts/templates/contacts/contact_detail.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1><a href="{% url 'contacts:contact-update' object.id %}">{{ object }}</a></h1>
<h2><a href="{% url 'contacts:email' object.id %}">emails</a></h2>
<ul>
{% for email in object.contactemail_set.all %}
<li><a href="{% url 'contacts:email-update' object.id email.id %}">{{ email }}</a></li>
{% empty %}
<p>no hay emails que mostrar</p>
{% endfor %}
</ul>
<a href="{% url 'contacts:email-create' object.id %}">agregar mail</a>

<h2><a href="{% url 'contacts:phone' object.id %}">telefonos</a></h2>
<ul>
{% for phone in object.contactphone_set.all %}
<li><a href="{% url 'contacts:phone-update' object.id phone.id %}">{{ phone }}</a></li>
{% empty %}
<p>no hay telefonos que mostrar</p>
{% endfor %}
</ul>
<a href="{% url 'contacts:phone-create' object.id %}">agregar telefono</a>
{% endblock subcontent %}

contacts/templates/contacts/contact_form.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar contacto">
</form>
{% endblock subcontent %}

contacts/templates/contacts/contact_list.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1>Contactos</h1>
<ul>
{% for contact in object_list %}
    <li><a href="{% url 'contacts:contact-detail' contact.id %}">{{ contact }}</a></li>
{% empty %}
    <li>No hay contactos que mostrar.</li>
{% endfor %}
</ul>
<a href="{% url 'contacts:contact-create' %}">agregar contacto</a>
{% endblock subcontent %}

contacts/templates/contacts/contactemail_detail.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1>{{ object.contact }}</h1>
<p>{{ object.email }}</p>
{% endblock subcontent %}

contacts/templates/contacts/contactemail_form.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar email">
</form>
{% endblock subcontent %}

contacts/templates/contacts/contactemail_list.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1>emails de {{ contact }}: </h1>
<ul>
{% for contact in object_list %}
    <li><a href="{% url 'contacts:email-update' contact.contact.id contact.id %}">{{ contact.email}}</a></li>
{% empty %}
    <li>No hay contactos que mostrar.</li>
{% endfor %}
</ul>
<a href="{% url 'contacts:email-create' contact.id %}">agregar mail</a>
{% endblock subcontent %}

contacts/templates/contacts/contactphone_detail.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1>{{ object.contact }}</h1>
<p>{{ object.phone_number }}</p>
{% endblock subcontent %}

contacts/templates/contacts/contactphone_form.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Guardar telefono">
</form>
{% endblock subcontent %}

contacts/templates/contacts/contactphone_list.html
{% extends "contacts/base.html" %}
{% block subcontent %}
<h1>emails de {{ contact }}: </h1>
<ul>
{% for contact in object_list %}
    <li><a href="{% url 'contacts:phone-update' contact.contact.id contact.id %}">{{ contact.phone_number}}</a></li>
{% empty %}
    <li>No hay contactos que mostrar.</li>
{% endfor %}
</ul>
<a href="{% url 'contacts:phone-create' contact.id %}">agregar telefono</a>
{% endblock subcontent %}

contacts/templates/contacts/email_detail.html
<h1>{{ object.contact }}</h1>
<p>{{ object.email }}</p>

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title></title>
	{% block base_css %}
	{% endblock base_css %}
	{% block css %}
	{% endblock css %}
</head>
<body>
	{% block content %}
	{% endblock content %}
	{% block base_js %}
	{% endblock base_js %}
	{% block js %}
	{% endblock js %}
</body>
<html>